import AuthProvider from "@/context/AuthProvider";
import "./globals.css"
import {createGlobalStyle} from "styled-components";
import StoreProvider from './StoreProvider'
import CartComponent from "@/components/DataFetcher";
import { Header } from "@/components";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">

      <AuthProvider>
        <StoreProvider>
          {/* <Header/> */}
          <body >{children}</body>
        </StoreProvider>
      </AuthProvider>
  
    </html>
  );
}